git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  overrideGpg: true
gui:
  authorColors:
    "Jonah Snider": "#ffbbcc"
  nerdFontsVersion: "3"
  showRandomTip: false
  showCommandLog: false
keybinding:
  universal:
    toggleRangeSelect: V
  commits:
    cherryPickCopy: c
    pasteCommits: v
