[tools]
bun = "latest"
"github:railwayapp/railpack" = "latest"
go = "latest"
java = "temurin-21"
node = "24"
python = "3.11"
ruff = "latest"
rust = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
trusted_config_paths = ["/Users/jonah.snider/conductor/workspaces/"]
