name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Install fish
        uses: fish-actions/install-fish@v1.2.0

      - name: Format fish files
        run: fish_indent -w private_dot_config/fish/**/*.fish

      - name: Run autofix.ci
        uses: autofix-ci/action@v1
